[buildPlans.Menlosevka]
family = "Menlosevka++"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.Menlosevka.variants]
  inherits = "ss04"

    [buildPlans.Menlosevka.variants.design]
    capital-q = "crossing"
    p = "earless-corner-serifless"
    q = "earless-corner-tailed-serifless"
    long-s = "bent-hook-diagonal-tailed-middle-serifed"
    eszet = "traditional-flat-hook-descending-middle-serifed"
    lower-alpha = "crossing"
    capital-gamma = "bottom-serifed"
    lower-iota = "flat-tailed"
    capital-lambda = "straight-top-serifed"
    lower-lambda = "tailed-turn"
    cyrl-capital-ka = "curly-bottom-right-serifed"
    cyrl-ka = "curly-bottom-right-serifed"
    cyrl-capital-u = "cursive-serifless"
    cyrl-u = "cursive-serifless"
    zero = "oval-slashed-split"
    three = "flat-top"

[buildPlans.Menlosevka.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Menlosevka.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.Menlosevka.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.Menlosevka.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.Menlosevka.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

#--------------------------------------------------------------


[buildPlans.Courievka]
family = "Courievka++"
spacing = "normal"
serifs = "slab"
noCvSs = true
exportGlyphNames = false
noLigation = true

[buildPlans.Courievka.variants.design]
capital-a = "straight-tri-serifed"
capital-g = "toothless-corner-serifed-capped"
capital-j = "serifed-both-sides"
capital-k = "curly-serifed"
capital-q = "detached-bend-tailed"
capital-r = "curly-serifed"
capital-w = "straight-flat-top-serifed"
g = "single-storey-flat-hook-serifed"
j = "flat-hook-serifed"
m = "serifed"
r = "corner-hooked-serifed"
t = "flat-hook"
x = "straight-serifed"
long-s = "flat-hook-double-serifed"
lower-delta = "flat-top"
lower-iota = "tailed"
capital-lambda = "straight-tri-serifed"
lower-pi = "tailed"
lower-tau = "tailed"
lower-chi = "straight-serifed"
cyrl-capital-zhe = "curly"
cyrl-zhe = "curly"
cyrl-capital-ka = "curly-serifed"
cyrl-ka = "curly-serifed"
cyrl-em = "flat-bottom-serifed"
cyrl-ef = "serifed"
cyrl-capital-ya = "standing-serifed"
cyrl-ya = "standing-serifed"
zero = "oval-dotted"
two = "straight-neck"
three = "two-arcs"
four = "closed"
five = "upright-arched"
six = "open-contour"
eight = "two-circles"
nine = "open-contour"
asterisk = "penta-high"
underscore = "high"
caret = "high"
brace = "straight"
guillemet = "straight"
number-sign = "slanted-tall"
ampersand = "upper-open"
at = "threefold"
dollar = "open"
cent = "open"
percent = "rings-continuous-slash"
question = "smooth"
pilcrow = "low"
micro-sign = "toothed-serifed"
lig-plus-chain = "without-notch"

[buildPlans.Courievka.weights.ExtraLight]
shape = 200
menu = 200
css = 200

[buildPlans.Courievka.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.Courievka.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Courievka.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.Courievka.widths.Normal]
shape = 720
menu = 5
css = "normal"

[buildPlans.Courievka.widths.Condensed]
shape = 600
menu = 3
css = "condensed"

[buildPlans.Courievka.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.Courievka.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
